// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteTask(arg1, arg2) {
  return window['go']['ui']['App']['ExecuteTask'](arg1, arg2);
}

export function GetHealth() {
  return window['go']['ui']['App']['GetHealth']();
}

export function GetKnowledgeGraph() {
  return window['go']['ui']['App']['GetKnowledgeGraph']();
}

export function GetSecurityAuditTrail() {
  return window['go']['ui']['App']['GetSecurityAuditTrail']();
}

export function GetSystemLogs() {
  return window['go']['ui']['App']['GetSystemLogs']();
}

export function GetTasks() {
  return window['go']['ui']['App']['GetTasks']();
}

export function ReadFileContent(arg1) {
  return window['go']['ui']['App']['ReadFileContent'](arg1);
}

export function ScanWorkspace() {
  return window['go']['ui']['App']['ScanWorkspace']();
}

export function TogglePermission(arg1, arg2) {
  return window['go']['ui']['App']['TogglePermission'](arg1, arg2);
}
