// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ui} from '../models';

export function ExecuteTask(arg1:string,arg2:string):Promise<ui.TaskDTO>;

export function GetHealth():Promise<Record<string, string>>;

export function GetKnowledgeGraph():Promise<ui.GraphDataDTO>;

export function GetSecurityAuditTrail():Promise<Array<ui.AuditDTO>>;

export function GetSystemLogs():Promise<Array<string>>;

export function GetTasks():Promise<Array<ui.TaskDTO>>;

export function ReadFileContent(arg1:string):Promise<string>;

export function ScanWorkspace():Promise<Array<ui.FileDTO>>;

export function TogglePermission(arg1:string,arg2:boolean):Promise<ui.PermissionStatusDTO>;
